# Generated by Django 4.2.1 on 2023-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcategory',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='addraspisanie',
            name='class_name',
            field=models.CharField(max_length=3, verbose_name='Класс'),
        ),
    ]
