# Generated by Django 4.2.1 on 2023-05-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема урока или название домашний задании')),
                ('nameTeacher', models.CharField(max_length=255, verbose_name='Ваше имя или имя учителя')),
                ('forTheClass', models.CharField(max_length=3, verbose_name='Для какого класса')),
                ('homework', models.TextField(verbose_name='Домашние задание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m/%d/', verbose_name='Фотография')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Домашняя задания',
                'verbose_name_plural': 'Домашнии задании',
                'ordering': ['-time_create', 'id'],
            },
        ),
    ]
